name: Automated Crypto Dashboard

on:
  schedule:
    # Runs at 11:00 UTC every day, which corresponds to 6:00 AM CDMX (America/Mexico_City)
    - cron: '0 11 * * *'
  workflow_dispatch:
    # Allow manual triggering via the GitHub Actions UI
    inputs: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate data
        run: |
          python collect_data.py
          python analysis_engine.py

      - name: Commit and push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Stage generated files
          git add data.json analysis.json email_summary.html
          # Create commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Automated data update"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send daily email
        run: |
          python send_email.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          TIMEZONE: America/Mexico_City
          EMAIL_SUBJECT: "💸 Crypto Investment Report"
